dataset_type: paired

teacher_config:
  wavlm_ckpt_path: ${oc.env:PASE_WAVLM_CKPT}
  output_layer: 24
  load_pretrained: true
  frozen: true

student_config:
  wavlm_ckpt_path: ${oc.env:PASE_DEWAVLM_CKPT}
  output_layer: 24
  load_pretrained: true
  frozen: false

vocoder_config:
  ckpt_path: ${oc.env:PASE_VOCODER_L24_CKPT}

DDP:
  world_size: 1

optimizer:
  lr: 0.001

scheduler:
  warmup_steps: 1000
  decay_until_step: 20000
  max_lr: 1e-5
  min_lr: 1e-6

samplerate: 16000

train_dataset:
  pair_csvs:
    - ${oc.env:PASE_TRAIN_PAIRS_CSV}
  wav_len: 4
  num_per_epoch: 0
  random_start: true
  default_fs: 16000
  mode: train
  normalize: true

train_dataloader:
  batch_size: 2
  num_workers: 4
  drop_last: true
  pin_memory: true

validation_dataset:
  pair_csvs:
    - ${oc.env:PASE_VALID_PAIRS_CSV}
  wav_len: 4
  num_per_epoch: 0
  random_start: false
  default_fs: 16000
  mode: validation
  normalize: true

validation_dataloader:
  batch_size: 1
  num_workers: 4
  drop_last: false
  pin_memory: true

trainer:
  epochs: 20
  save_checkpoint_interval: 5
  clip_grad_norm_value: 3.0
  exp_path: ${oc.env:PASE_EXPERIMENT_ROOT}/exp_DeWavLM_paired
  resume: false
  resume_datetime: ""
